title: Newbie Blog
author: RickSilv
email: rickleonharti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a simple one, to understand the basics of GitHub Pages.
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
